server:
  port: 8080

spring:
  application:
    name: techcup-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # service indentity
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # service users
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter

        # service teams
        - id: teams-service
          uri: http://localhost:8083
          predicates:
            - Path=/teams/**
          filters:
            - AuthFilter

        # service tournaments
        - id: tournaments-service
          uri: http://localhost:8084
          predicates:
            - Path=/tournaments/**
          filters:
            - AuthFilter

        # service competitions
        - id: competition-service
          uri: http://localhost:8085
          predicates:
            - Path=/competition/**
          filters:
            - AuthFilter

# password encoder strength
app:
  jwt:
    secret: techcup-clave-secreta-minimo-256-bits-cambiar-en-produccion